/* ******************************
AUTHOR :VS NIKHIL MAHESWAR
PROGRAM:GUESS THE RANDOM NUMBER GENERATED BY THE COMPILER
DATE:24-01-2022
********************************** */
import java.util.Random;
import java.util.Scanner;
class game {
  public   int num_of_gues = 0,randnum,GUESS,op;
    game() // GENERATING RANDOM NUMBER BY CREATING OBJECT OF RANDOM CLASS
    {
Random rd=new Random();
randnum=rd.nextInt(10);
    }
  public   void takeuserinput(int GUESS ) {
this.GUESS=GUESS; 
    }

  public   void iscorrectnum()
    {
if(GUESS>randnum)
{
    System.out.println("OOPS...You have chosen a bigger number");
    num_of_gues++;
    System.out.println("number of guess = "+num_of_gues);
}
else if (GUESS<randnum)
        {
            num_of_gues++;
            System.out.println("OOPs...you have chosen a smaller number");
            System.out.println("number of guess = "+num_of_gues);
        }
else
{
    Scanner s=new Scanner(System.in);
    System.out.println("Congrats!! guess is correct");
    num_of_gues++;
    System.out.println("number of guess = "+num_of_gues);

}
    }
}
public class Randamnumber {
    public static void main(String[] args) {
        Scanner s=new Scanner(System.in);
        game p1=new game();
int op=1;
while(op==1)
{
    System.out.println("enter your guess number");
    int ne=s.nextInt();
    p1.takeuserinput(ne);
    p1.iscorrectnum();
    System.out.println("press 1 to continue with game \n press 0 to exit!!!");
    op=s.nextInt();
}
    }
}
